export { default as AboutPrimer } from "./AboutPrimer"
export { default as ContactUs } from "./ContactUs"
export { default as CourseBullets } from "./CourseBullets"
export { default as HeroHeader } from "./HeroHeader"
export { default as HeroImage } from "./HeroImage"
export { default as InfoForm } from "./InfoForm"
export { default as Testimonial } from "./Testimonial"
