export { default as HeroHeader } from "./HeroHeader"
export { default as HeroImage } from "./HeroImage"
export { default as Ratings } from "./Ratings"
export { default as Differences } from "./Differences"
export { default as Testimonial } from "./Testimonial"
export { default as VideoModal } from "./VideoModal"
