export {default as Header} from "./Header.js"
export {default as VideoModal} from "./VideoModal.js"
export {default as ScholarshipDetails} from "./ScholarshipDetails.js"
export {default as Details}from "./Details.js"
export {default as InternshipDetails} from "./InternshipDetails.js"
export {default as Companies} from "./Companies.js"
export {default as Ratings} from "./Ratings.js"
export {default as Testimonial} from "./Testimonial.js"
export {default as MakeALeap} from "./MakeALeap.js"